services:
  tinyalloc:
    image: softsec/tinyalloc
    build: .
    pull_policy: never
    hostname: tinyalloc
    platform: "linux/amd64"
    ports:
      - 127.0.0.1:1024:1024
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
