services:
  ragnarok:
    image: softsec/ragnarok
    build: .
    pull_policy: never
    hostname: ragnarok
    platform: "linux/amd64"
    ports:
      - 127.0.0.1:1024:1024
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
