# Please see RUNNING.md for details on how to run this task.

services:
  practice-1:
    extends:
      file: base.yml
      service: practice-1
    image: softsec/debug/practice-1
    build:
      target: debug
    cap_add:
      - SYS_PTRACE
